env: "gymma"

env_args:
  key: null
  time_limit: 100
  pretrained_wrapper: null

test_greedy: True
test_nepisode: 500
test_interval: 5000
log_interval: 5000 # Log summary of stats after every {} timesteps
runner_log_interval: 50 # Log runner stats (not test stats) every {} timesteps
learner_log_interval: 50 # Log training stats every {} timesteps
t_max: 500000 # Stop running after this many timesteps
save_model_interval: 5000 # Save models after this many timesteps
#checkpoint_path: "results/models/qmix_seed287395591_DVRPEnv-v0_2023-01-18 20:22:04.752063/"
evaluate: False


save_model: False # Save the models to disk
